### ISSUE TITLE
Mobile devices don't display chat but only the menu

### ISSUE THREAD

**Issue by gtomitsuka** [gtomitsuka/montreus-chat#17]
Note: On mobile devices we can do like SE and hide the menu, but only display the messages. What do you guys think?
![Screenshot](https://cloud.githubusercontent.com/assets/10295671/6091962/45bc393c-aec6-11e4-8b56-197619aba4f0.png)

**Comment by pczern** [comment]
Do you test it local? Because of the public folder i saw this too. But normal it should only appear if you click the menu button

**Comment by gtomitsuka** [comment]
Also, another problem with long usernames like mine are:
![Computer](https://cloud.githubusercontent.com/assets/10295671/6091974/ae1fcb56-aec6-11e4-91eb-457320068ef8.png)

**Comment by gtomitsuka** [comment]
No, I'm testing it with `node app.js`

**Comment by pczern** [comment]
Here are some images
![montreus chat](https://cloud.githubusercontent.com/assets/10871302/6091995/baa286e2-aec7-11e4-9003-acccd7a09a02.png)
![montreus chat 1](https://cloud.githubusercontent.com/assets/10871302/6091997/d11a928e-aec7-11e4-92f8-179198e07e39.png)

**Comment by gtomitsuka** [comment]
For reference on how it looks with messages:
![screen shot 2015-02-07 at 12 59 07 pm](https://cloud.githubusercontent.com/assets/10295671/6092024/23581b42-aec9-11e4-95ee-44c84dc2c11b.png)

**Comment by gtomitsuka** [comment]
Fixed as of v1.5.2, or #20.
