### ISSUE TITLE
Displays No Javascript error when Javascript is indeed enabled.

### ISSUE THREAD

**Issue by gtomitsuka** [gtomitsuka/montreus-chat#30]
![screen shot 2015-02-10 at 3 54 59 pm](https://cloud.githubusercontent.com/assets/10295671/6129276/673f331a-b13d-11e4-812b-6ead0b733734.png)

**Comment by pczern** [comment]
Maybe you didn't restart server or cleaning cache? Because it works.[image:
Inline-Bild 1]

2015-02-10 15:56 GMT+01:00 Gabriel Tomitsuka notifications@github.com:

> [image: screen shot 2015-02-10 at 3 54 59 pm]
> https://cloud.githubusercontent.com/assets/10295671/6129276/673f331a-b13d-11e4-812b-6ead0b733734.png

**Comment by gtomitsuka** [comment]
Sorry for the inconvenience! It was indeed my cache.
