### ISSUE TITLE
Non-responsive design

### ISSUE THREAD

**Issue by gtomitsuka** [gtomitsuka/montreus-chat#59]
Website not functional in iOS.

![screen shot 2015-02-25 at 3 31 52 pm](https://cloud.githubusercontent.com/assets/10295671/6372313/82bbb902-bd03-11e4-8d1d-b575e09cacf4.png)

**Comment by pczern** [comment]
On chrome for android there's the same bug. Some suggestions to solve this?

**Comment by emtjoshhart** [comment]
What do you mean?

On Thu, Feb 26, 2015 at 2:10 AM, speedDeveloper <notifications@github.com>
wrote:

> On chrome for android there's the same bug. Some suggestions to solve this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gtomitsuka/montreus-chat/issues/59#issuecomment-76066247>
> .
>



-- 
Joshua Hart
Diplomatic Medic
Kabul, Afghanistan

Confidentiality Notice: This email message (and any attachments) contains
information which may be privileged or confidential, or exempt from
disclosure under applicable law. If the reader of this message is not the
intended recipient, or the employee or agent responsible for delivering the
message to the intended recipient, you are hereby notified that any
dissemination, distribution, retention, archiving, or copying of this
communication is strictly prohibited. If you have received this e-mail (and
any attachments) in error, please notify us immediately by return e-mail to
the sender.

**Comment by emtjoshhart** [comment]
Im on chat...can you not get on?

On Thu, Feb 26, 2015 at 2:37 AM, Joshua Hart <emt.joshhart@gmail.com> wrote:

> What do you mean?
>
> On Thu, Feb 26, 2015 at 2:10 AM, speedDeveloper <notifications@github.com>
> wrote:
>
>> On chrome for android there's the same bug. Some suggestions to solve
>> this?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gtomitsuka/montreus-chat/issues/59#issuecomment-76066247>
>> .
>>
>
>
>
> --
> Joshua Hart
> Diplomatic Medic
> Kabul, Afghanistan
>
> Confidentiality Notice: This email message (and any attachments) contains
> information which may be privileged or confidential, or exempt from
> disclosure under applicable law. If the reader of this message is not the
> intended recipient, or the employee or agent responsible for delivering the
> message to the intended recipient, you are hereby notified that any
> dissemination, distribution, retention, archiving, or copying of this
> communication is strictly prohibited. If you have received this e-mail (and
> any attachments) in error, please notify us immediately by return e-mail to
> the sender.
>
>


-- 
Joshua Hart
Diplomatic Medic
Kabul, Afghanistan

Confidentiality Notice: This email message (and any attachments) contains
information which may be privileged or confidential, or exempt from
disclosure under applicable law. If the reader of this message is not the
intended recipient, or the employee or agent responsible for delivering the
message to the intended recipient, you are hereby notified that any
dissemination, distribution, retention, archiving, or copying of this
communication is strictly prohibited. If you have received this e-mail (and
any attachments) in error, please notify us immediately by return e-mail to
the sender.

**Comment by pczern** [comment]
Do you see the picture posted from GT? That's the bug on mobile devices.

**Comment by emtjoshhart** [comment]
i see the pic associated with his comment "gabriel.tomitsuka: That’s a
screen-shot from my server in N. Virginia receiving the messages from my
iPhone :)"


On Thu, Feb 26, 2015 at 2:39 AM, speedDeveloper <notifications@github.com>
wrote:

> Do you see the picture posted from GT? That's the bug on mobile devices.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gtomitsuka/montreus-chat/issues/59#issuecomment-76071405>
> .
>



-- 
Joshua Hart
Diplomatic Medic
Kabul, Afghanistan

Confidentiality Notice: This email message (and any attachments) contains
information which may be privileged or confidential, or exempt from
disclosure under applicable law. If the reader of this message is not the
intended recipient, or the employee or agent responsible for delivering the
message to the intended recipient, you are hereby notified that any
dissemination, distribution, retention, archiving, or copying of this
communication is strictly prohibited. If you have received this e-mail (and
any attachments) in error, please notify us immediately by return e-mail to
the sender.

**Comment by emtjoshhart** [comment]
Is that the one?

On Thu, Feb 26, 2015 at 2:42 AM, Joshua Hart <emt.joshhart@gmail.com> wrote:

> i see the pic associated with his comment "gabriel.tomitsuka: That’s a
> screen-shot from my server in N. Virginia receiving the messages from my
> iPhone :)"
>
>
> On Thu, Feb 26, 2015 at 2:39 AM, speedDeveloper <notifications@github.com>
> wrote:
>
>> Do you see the picture posted from GT? That's the bug on mobile devices.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gtomitsuka/montreus-chat/issues/59#issuecomment-76071405>
>> .
>>
>
>
>
> --
> Joshua Hart
> Diplomatic Medic
> Kabul, Afghanistan
>
> Confidentiality Notice: This email message (and any attachments) contains
> information which may be privileged or confidential, or exempt from
> disclosure under applicable law. If the reader of this message is not the
> intended recipient, or the employee or agent responsible for delivering the
> message to the intended recipient, you are hereby notified that any
> dissemination, distribution, retention, archiving, or copying of this
> communication is strictly prohibited. If you have received this e-mail (and
> any attachments) in error, please notify us immediately by return e-mail to
> the sender.
>
>


-- 
Joshua Hart
Diplomatic Medic
Kabul, Afghanistan

Confidentiality Notice: This email message (and any attachments) contains
information which may be privileged or confidential, or exempt from
disclosure under applicable law. If the reader of this message is not the
intended recipient, or the employee or agent responsible for delivering the
message to the intended recipient, you are hereby notified that any
dissemination, distribution, retention, archiving, or copying of this
communication is strictly prohibited. If you have received this e-mail (and
any attachments) in error, please notify us immediately by return e-mail to
the sender.

**Comment by emtjoshhart** [comment]
Just made this Icon, been taking some designing school!  ;)

On Thu, Feb 26, 2015 at 2:42 AM, Joshua Hart <emt.joshhart@gmail.com> wrote:

> Is that the one?
>
> On Thu, Feb 26, 2015 at 2:42 AM, Joshua Hart <emt.joshhart@gmail.com>
> wrote:
>
>> i see the pic associated with his comment "gabriel.tomitsuka: That’s a
>> screen-shot from my server in N. Virginia receiving the messages from my
>> iPhone :)"
>>
>>
>> On Thu, Feb 26, 2015 at 2:39 AM, speedDeveloper <notifications@github.com
>> > wrote:
>>
>>> Do you see the picture posted from GT? That's the bug on mobile devices.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/gtomitsuka/montreus-chat/issues/59#issuecomment-76071405>
>>> .
>>>
>>
>>
>>
>> --
>> Joshua Hart
>> Diplomatic Medic
>> Kabul, Afghanistan
>>
>> Confidentiality Notice: This email message (and any attachments) contains
>> information which may be privileged or confidential, or exempt from
>> disclosure under applicable law. If the reader of this message is not the
>> intended recipient, or the employee or agent responsible for delivering the
>> message to the intended recipient, you are hereby notified that any
>> dissemination, distribution, retention, archiving, or copying of this
>> communication is strictly prohibited. If you have received this e-mail (and
>> any attachments) in error, please notify us immediately by return e-mail to
>> the sender.
>>
>>
>
>
> --
> Joshua Hart
> Diplomatic Medic
> Kabul, Afghanistan
>
> Confidentiality Notice: This email message (and any attachments) contains
> information which may be privileged or confidential, or exempt from
> disclosure under applicable law. If the reader of this message is not the
> intended recipient, or the employee or agent responsible for delivering the
> message to the intended recipient, you are hereby notified that any
> dissemination, distribution, retention, archiving, or copying of this
> communication is strictly prohibited. If you have received this e-mail (and
> any attachments) in error, please notify us immediately by return e-mail to
> the sender.
>
>


-- 
Joshua Hart
Diplomatic Medic
Kabul, Afghanistan

Confidentiality Notice: This email message (and any attachments) contains
information which may be privileged or confidential, or exempt from
disclosure under applicable law. If the reader of this message is not the
intended recipient, or the employee or agent responsible for delivering the
message to the intended recipient, you are hereby notified that any
dissemination, distribution, retention, archiving, or copying of this
communication is strictly prohibited. If you have received this e-mail (and
any attachments) in error, please notify us immediately by return e-mail to
the sender.

**Comment by emtjoshhart** [comment]
Sorry, here's the larger one:

On Thu, Feb 26, 2015 at 2:48 AM, Joshua Hart <emt.joshhart@gmail.com> wrote:

> Just made this Icon, been taking some designing school!  ;)
>
> On Thu, Feb 26, 2015 at 2:42 AM, Joshua Hart <emt.joshhart@gmail.com>
> wrote:
>
>> Is that the one?
>>
>> On Thu, Feb 26, 2015 at 2:42 AM, Joshua Hart <emt.joshhart@gmail.com>
>> wrote:
>>
>>> i see the pic associated with his comment "gabriel.tomitsuka: That’s a
>>> screen-shot from my server in N. Virginia receiving the messages from my
>>> iPhone :)"
>>>
>>>
>>> On Thu, Feb 26, 2015 at 2:39 AM, speedDeveloper <
>>> notifications@github.com> wrote:
>>>
>>>> Do you see the picture posted from GT? That's the bug on mobile devices.
>>>>
>>>> —
>>>> Reply to this email directly or view it on GitHub
>>>> <https://github.com/gtomitsuka/montreus-chat/issues/59#issuecomment-76071405>
>>>> .
>>>>
>>>
>>>
>>>
>>> --
>>> Joshua Hart
>>> Diplomatic Medic
>>> Kabul, Afghanistan
>>>
>>> Confidentiality Notice: This email message (and any attachments)
>>> contains information which may be privileged or confidential, or exempt
>>> from disclosure under applicable law. If the reader of this message is not
>>> the intended recipient, or the employee or agent responsible for delivering
>>> the message to the intended recipient, you are hereby notified that any
>>> dissemination, distribution, retention, archiving, or copying of this
>>> communication is strictly prohibited. If you have received this e-mail (and
>>> any attachments) in error, please notify us immediately by return e-mail to
>>> the sender.
>>>
>>>
>>
>>
>> --
>> Joshua Hart
>> Diplomatic Medic
>> Kabul, Afghanistan
>>
>> Confidentiality Notice: This email message (and any attachments) contains
>> information which may be privileged or confidential, or exempt from
>> disclosure under applicable law. If the reader of this message is not the
>> intended recipient, or the employee or agent responsible for delivering the
>> message to the intended recipient, you are hereby notified that any
>> dissemination, distribution, retention, archiving, or copying of this
>> communication is strictly prohibited. If you have received this e-mail (and
>> any attachments) in error, please notify us immediately by return e-mail to
>> the sender.
>>
>>
>
>
> --
> Joshua Hart
> Diplomatic Medic
> Kabul, Afghanistan
>
> Confidentiality Notice: This email message (and any attachments) contains
> information which may be privileged or confidential, or exempt from
> disclosure under applicable law. If the reader of this message is not the
> intended recipient, or the employee or agent responsible for delivering the
> message to the intended recipient, you are hereby notified that any
> dissemination, distribution, retention, archiving, or copying of this
> communication is strictly prohibited. If you have received this e-mail (and
> any attachments) in error, please notify us immediately by return e-mail to
> the sender.
>
>


-- 
Joshua Hart
Diplomatic Medic
Kabul, Afghanistan

Confidentiality Notice: This email message (and any attachments) contains
information which may be privileged or confidential, or exempt from
disclosure under applicable law. If the reader of this message is not the
intended recipient, or the employee or agent responsible for delivering the
message to the intended recipient, you are hereby notified that any
dissemination, distribution, retention, archiving, or copying of this
communication is strictly prohibited. If you have received this e-mail (and
any attachments) in error, please notify us immediately by return e-mail to
the sender.

**Comment by pczern** [comment]
Yes! GT I think chrome for android and your iOS webbrowser (probably safari) aren't compatible with localStorage. That means that this variable is undefined and an error is thrown in our script which destroys the whole design.

**Comment by emtjoshhart** [comment]
lol, i have no idea what ya'll mean, lol

On Thu, Feb 26, 2015 at 2:51 AM, speedDeveloper <notifications@github.com>
wrote:

> Yes! GT I think chrome for android and your iOS webbrowser (probably
> safari) aren't compatible with localStorage. That means that this variable
> is undefined and an error is thrown in our script which destroys the whole
> design.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gtomitsuka/montreus-chat/issues/59#issuecomment-76073519>
> .
>



-- 
Joshua Hart
Diplomatic Medic
Kabul, Afghanistan

Confidentiality Notice: This email message (and any attachments) contains
information which may be privileged or confidential, or exempt from
disclosure under applicable law. If the reader of this message is not the
intended recipient, or the employee or agent responsible for delivering the
message to the intended recipient, you are hereby notified that any
dissemination, distribution, retention, archiving, or copying of this
communication is strictly prohibited. If you have received this e-mail (and
any attachments) in error, please notify us immediately by return e-mail to
the sender.
