### ISSUE TITLE
XSS

### ISSUE THREAD

**Issue by matthewr6** [gtomitsuka/montreus-chat#6]
HTML <> tag characters are not filtered.

**Comment by matthewr6** [comment]
Suggested solution - http://stackoverflow.com/questions/1787322/htmlspecialchars-equivalent-in-javascript

**Comment by gtomitsuka** [comment]
I believe that on the next update it should still allow HTML tags, however without Scripts and some other kinds of them

**Comment by matthewr6** [comment]
You'd just filter things like &lt;script&gt;, then

**Comment by matthewr6** [comment]
It's still not fixed - usernames can cause the system to break

**Comment by gtomitsuka** [comment]
Done :)
